### ISSUE TITLE
Can't be sudo in ubuntu 14.04 in term2 -v 0.9.5

### ISSUE THREAD

**Issue by asiniy** [f/atom-term2#118]
IE

This command in gnome-terminal ask me for a password:

``` sh
sudo -i
```

And in the term2 `0.9.5` I get this strange message:

```
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

All works good in `0.9.2`

**Comment by MoOx** [comment]
Still relevant ? I cannot reproduce (sudo -i is working)

**Comment by asiniy** [comment]
Yep. I still get the same error.

Are you ubuntu user?

**Comment by MoOx** [comment]
OS X using zsh.

**Comment by asiniy** [comment]
I think that's not this plugin, but the whole `atom-editor` bug. But I'm not sure

**Comment by MoOx** [comment]
Can you try this workaround ? https://github.com/webBoxio/atom-term2/issues/50#issuecomment-119881421

**Comment by ethe** [comment]
have the same problem

**Comment by asiniy** [comment]
@ethe, this seems to be trouble of the atom editor.. Please write here about this bug: https://github.com/atom/atom/issues/6702

**Comment by ethe** [comment]
@asiniy thanks, i have reported this problem under your issue
