### ISSUE TITLE
Support/inherit Atom theme.

### ISSUE THREAD

**Issue by iclanzan** [f/atom-term2#121]
It would be nice if by default terminals used colors from the currently active Atom theme.

**Comment by numbcoder** [comment]
+1

**Comment by nemonweb** [comment]
+1

**Comment by preynal** [comment]
+1

**Comment by MoOx** [comment]
For now background is inherited.
Someone tried something https://github.com/adammw/atom-term2/commit/bd4fb7bf84fc99d66905e5ff05faea39122f2bee

**Comment by MoOx** [comment]
Problem is, we don't know how to match ansi color to current theme. This will require some color comparison (to know what "blue" to use, what "red" to use etc.) This won't be easy...

**Comment by f** [comment]
It's too hard to do. The bash output comes with some color codes and pty converts them to html tags with inline CSS like `<span style="font-weight:bold;color:#d75f00;">hello</span>` which is really hard to map. We should work on http://github.com/f/atom-term.js to convert inline CSS to class names I guess.

**Comment by MoOx** [comment]
I think it's almost impossible to get a relevant color mapping. If a theme is just some shades of grey... We should close + add some comments in the README imo

**Comment by f** [comment]
Totally agree :+1: . Would you write a note to README, since my English is not that fluent? :) And we may close this issue then.
