### ISSUE TITLE
Cannot type tilde char (~)

### ISSUE THREAD

**Issue by MoOx** [f/atom-term2#127]
I wanted to type `git reset HEAD~1` but when I type alt+n, then space (works everywhere - here or in a classic terminal) it just doesn't work.

Any idea why ?

**Comment by leojrfs** [comment]
Confirmed.

cannot type '~'

**Comment by blimmer** [comment]
`alt+n` is like `alt+e` on OS X, which is to type characters like ñ. I can confirm that neither of these work in Term2, but why not just use the tilde character on the keyboard?

**Comment by MoOx** [comment]
On azerty keyboard, there is no ~ key :)

A workaround is to use fn + ← (delete) to make a ~ appear

**Comment by ebonet** [comment]
Same situation on linux

**Comment by TimeForAChange** [comment]
Same here. I have package keyboard-localization installed. When I try to use that package's keymap-generator the tilde character is unavailable too, nothing is generated but  a key down event is present. Below is that dialog's status just after I press "ALT-GR - +" - the location of the tilde character on this German keyboard.

![screenshot](https://cloud.githubusercontent.com/assets/199179/9683548/61b027da-5311-11e5-9df8-1f71618b9be5.png)

**Comment by fredguth** [comment]
+1 with this problem.

when I type: `cd ~`
it actually goes to my directory, but I can't see the tilde while I typed.

**Comment by mdio** [comment]
I also have this problem on Windows 8, German keyboard layout with Atom 1.3.1 and only prepacked packages (except for expand-region).
On other applications the ~ works fine.

**Comment by DomS23** [comment]
+1 with this problem.

German keyboard layout. If i'm using alt+~ key (which is the key with the star next to the enter key) no tilde appears.

If two windows are displayed next to each other e.g. for markdown preview, the right window gehts shrinked in width with this key command.

**Comment by tknerr** [comment]
@fredguth that is probably because `cd` without any args also changes to your home directory

I'm seeing this in plain atom 1.7.3 too when editing a text file for example.

Any known workarounds for this yet?

**Comment by tobiasschuerg** [comment]
Same for me on Atom 1.10 with a german keyboard
