### ISSUE TITLE
Ctrl-C sends literal ^C instead of SIGTERM

### ISSUE THREAD

**Issue by hexchain** [f/atom-term2#13]
This problem is found in Atom 0.99.0 on Arch Linux. When Ctrl-C is pressed, the process inside terminal is not terminated. Instead, ^C shows up.

**Comment by aharonp** [comment]
I'm also seeing this issue.

**Comment by f** [comment]
You should try `Ctrl-D` to do it. I'll try to make `Ctrl-C` works as well.
