### ISSUE TITLE
Installing failed because of pty.js on Windows

### ISSUE THREAD

**Issue by juanscv** [f/atom-term2#132]
I just tried to install in Atom directly from Settings and get this error

```
> pty.js@0.2.7-1 install C:\Users\juan\AppData\Local\Temp\apm-install-dir-115427-13908-5p0c5e\node_modules\term2\node_modules\pty.js
> node-gyp rebuild


C:\Users\juan\AppData\Local\Temp\apm-install-dir-115427-13908-5p0c5e\node_modules\term2\node_modules\pty.js>node "C:\Users\juan\AppData\Local\atom\app-0.201.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\juan\\AppData\\Local\\atom\\app-0.201.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\juan\\AppData\\Local\\atom\\app-0.201.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\juan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\juan\\.atom\\.apmrc" "install" "C:\\Users\\juan\\AppData\\Local\\Temp\\d-115427-13908-1yy788h\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.7-1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.7-1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
```

My Atom version is 0.201.0

**Comment by nafSadh** [comment]
I got same error even with apm.

**Comment by ahukkanen** [comment]
Same error here in Windows 7.

**Comment by ppalladino** [comment]
Same on windows 7

**Comment by MoOx** [comment]
> npm ERR! This is most likely a problem with the pty.js package,

You should report this error to pty.js please

**Comment by ahukkanen** [comment]
It seems that they do not include the windows binaries in the pty package. Let's make some noise here:
https://github.com/chjj/pty.js/issues/45

**Comment by lancelot** [comment]
same installation failure on ubuntu 14.04LTS, Atom 1.0.0 with term2 v.0.9.12

<pre>
> pty.js@0.2.8 install /tmp/apm-install-dir-11569-8586-1ymq6vl/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-11569-8586-1ymq6vl/node_modules/term2/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory `/tmp/apm-install-dir-11569-8586-1ymq6vl/node_modules/term2/node_modules/pty.js/build'

make: g++: Command not found
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-43-generic
gyp ERR! command "node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11569-8586-1ymq6vl/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.16.0-43-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/lancelot/.atom/.apm/.apmrc" "--userconfig" "/home/lancelot/.atom/.apmrc" "install" "/tmp/d-11569-8586-8vkkkz/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11569-8586-1ymq6vl/npm-debug.log
</pre>

**Comment by MoOx** [comment]
Hum that's weird it didn't work on a *nix platform... Can you try to install pty.js directly ?

**Comment by lancelot** [comment]
I looked into the error log. Turned out it was because my system don't have g++.
Problem fixed after installing g++....my bad and thanks for reply

**Comment by TheVonLeon** [comment]
I get this issue as well for windows. Very, very frustrating.

**Comment by codehotter** [comment]
If you're desperate to try it out before we get an official working version... Here's what I did to get it to MOSTLY work on Windows 8.1. My arrow keys aren't working inside vim or less. They work in the shell for history. I don't know if this problem is related to anything I did to get it to work.

0. Install python 2.7 (make sure it's in path)
1. Install Microsoft Visual Studio 2013 Community Edition (NOT 2015)
2. git clone https://github.com/codehotter/atom-term2
3. Add ATOM_DIR\atom\resources\app\apm\bin to path
4. apm install
5. run command prompt as administrator, navigate to atom-term2 directory again
6. apm link .

I added this to my config to make it work with bash instead of powershell:

```
  term2:
    shellOverride: "cmd.exe"
    shellArguments: "/c set CHERE_INVOKING=1 && E:/msys64/usr/bin/bash.exe --login"
    titleTemplate: "Terminal"
```

My fork has the following changes:

1. Patch pty.js to make it compile at all ( https://github.com/codehotter/pty.js ). Updated to winpty latest version which fixes some compile errors, change submodule to subtree (couldn't get submodule to work) and hacked pty.cc to fix some more compile errors related to newer node version. Note: inexperienced c++ programmer. Don't really know what I'm doing.

2. The following patches to atom-term2. Note: even though it's not c++ I still don't really know what I'm doing.

Use my fork of pty.js that compiles:

```
diff --git a/package.json b/package.json
index 9c7bc3d..d99a340 100644
--- a/package.json
+++ b/package.json
@@ -23,6 +23,6 @@
     "debounce": "0.0.3",
     "fs-plus": "^2.2.3",
     "keypather": "^1.3.2",
-    "pty.js": "^0.2.13"
+    "pty.js": "git://github.com/codehotter/pty.js.git#update-winpty-0.2.13"
   }
 }
```

Fix https://github.com/webBoxio/atom-term2/issues/15

```
diff --git a/index.coffee b/index.coffee
index c88d39b..f242cd5 100644
--- a/index.coffee
+++ b/index.coffee
@@ -90,6 +90,7 @@ module.exports =
       shellArguments:
         type: 'string'
         default: do ({SHELL, HOME}=process.env)->
+          return '' unless SHELL
           switch path.basename SHELL.toLowerCase()
             when 'bash' then "--init-file #{path.join HOME, '.bash_profile'}"
             when 'zsh'  then ""
```

Fix path to powershell.exe

```
diff --git a/lib/pty.coffee b/lib/pty.coffee
index 64633f9..770ffef 100644
--- a/lib/pty.coffee
+++ b/lib/pty.coffee
@@ -9,7 +9,7 @@ module.exports = (ptyCwd, sh, args) ->
   else
       if process.platform is 'win32'
         path = require 'path'
-        shell = path.resolve(process.env.SystemRoot, 'WindowsPowerShell', 'v1.0', 'powershell.exe')
+        shell = path.resolve(process.env.SystemRoot, 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe')
       else
         shell = process.env.SHELL
```

**Comment by rofrol** [comment]
`apm install` didn't work inside atom-term2. I got this error https://github.com/chjj/pty.js/issues/131

I tried to use ptyw.js https://github.com/chjj/pty.js/issues/131#issuecomment-157041799

I've changed the name in package.json to pty.js. Then cmd.exe as admin:

Because i couldn't just copy ptyw.js as pty.js inside `<path_to_atom-term2>\node_modules`, I needed to make a link:

    cd <path_to_ptyw.js>
    apm install
    apm link .
    mklink /d <path_to_atom-term2>\node_modules\pty.js <path_to_ptyw.js>

Then:

    cd <path_to_atom-term2>
    apm install
    apm link .

It managed to install term2, but when I tried to run it I got:

```
Failed to activate the term2 package
Cannot read property 'toLowerCase' of undefined
Hide Stack Trace
TypeError: Cannot read property 'toLowerCase' of undefined
    at file:///C:/Users/frolow/.atom/dev/atom-term2/index.coffee:93:37
    at Object.<anonymous> (file:///C:/Users/frolow/.atom/dev/atom-term2/index.coffee:92:18)
    at Object.<anonymous> (file:///C:/Users/frolow/.atom/dev/atom-term2/index.coffee:1:1)
    at Module._compile (C:\installed\AtomBeta\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\installed\AtomBeta\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\installed\AtomBeta\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\installed\AtomBeta\resources\app.asar\src\package.js:721:27)
    at Package.module.exports.Package.activateNow (C:\installed\AtomBeta\resources\app.asar\src\package.js:173:16)
    at C:\installed\AtomBeta\resources\app.asar\src\package.js:801:25
    at Emitter.module.exports.Emitter.emit (C:\installed\AtomBeta\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\installed\AtomBeta\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\installed\AtomBeta\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\installed\AtomBeta\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\installed\AtomBeta\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
The error was thrown from the term2 package. This issue has already been reported.
```

And the link to https://github.com/f/atom-term2/issues/205
