### ISSUE TITLE
Open File in Terminal Fails

### ISSUE THREAD

**Issue by machste** [f/atom-term2#133]
Opening an existing file in the terminal by typing
```
$ atom test.c                                                                                  
$ /usr/share/atom/atom: bad option: --executed-from=/home/user/Projects                      
/usr/share/atom/atom: bad option: --pid=12196
$
```
fails badly.

Atom: 0.204.0 on Linux Mint 16 64bit

**Comment by johnbellessa** [comment]
I'm having this issue too. Surely this has to be a fairly common use case. Is there no one else having this problem?

Atom 1.0.0 on Ubuntu 14.04 Server (with xfce)

**Comment by moranje** [comment]
Same here on `atom .` I get the following error:

```
➜  atom .
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```

**Comment by f** [comment]
It's not possible due to Atom's internals. We cannot make anything about it, for now. Added to todos.
