### ISSUE TITLE
NODE_ENV=production environment variable leaks into shell

### ISSUE THREAD

**Issue by MattKunze** [f/atom-term2#144]
I was working in a project, running `npm install`, and running into all sorts of problems and tracked it down to the fact that npm doesn't install dev dependencies when NODE_ENV is set to production. I'm guessing other atom-specific environment variables are leaking into the shell as well, it would be nice if the embedded shell behaved the same as when launched directly.

**Comment by MattKunze** [comment]
![image](https://cloud.githubusercontent.com/assets/421270/8469445/0bbaa596-2038-11e5-82fd-67dc1583b004.png)

**Comment by chrisjaure** [comment]
I ran into this issue too. Really messed me up when doing an `npm install`.

**Comment by MoOx** [comment]
I got it too. I defined an empty value in my .zshrc. Not sure how to fix this properly. Maybe we can start by exporting an empty NODE_ENV? Not sure how to do this.

**Comment by chrisjaure** [comment]
Looks like this can be fixed by not passing process.env straight in here: https://github.com/webBoxio/atom-term2/blob/master/lib/pty.coffee#L29

**Comment by MoOx** [comment]
You think we should drop this line ? Or just remove NODE_ENV ?

**Comment by chrisjaure** [comment]
Passing in an empty array worked for me locally. Otherwise removing the whole line seemed to pass in current env variables by default so `NODE_ENV` was still `production`.

**Comment by codalytics-volusion** [comment]
I ran into this issue too.

**Comment by niahmiah** [comment]
I also ran into this. 

It seems like you could just delete process.env.NODE_ENV before passing process.env in. Haven't tried it yet though.

**Comment by arisAlexis** [comment]
I was also using node-debugger package when unexpectedly my server script started in production mode.if its not necessary for atom then dont export it
