### ISSUE TITLE
Keyboard input doesn't work after resize

### ISSUE THREAD

**Issue by ssfrr** [f/atom-term2#147]
When I open a split terminal I can type in text just fine, but then as soon as I resize the split the keyboard input stops working. I click the terminal and start typing and no text shows up.

**Comment by MoOx** [comment]
Sorry I cannot reproduce. I opened a terminal on the left, typed a little, resize atom (which resize the pane right ?), clicked (I can type), resize the pane (from the middle, since my terminal pane was on the left), clicked (I can still type)...

**Comment by ssfrr** [comment]
Oops, I see what's going on. I wasn't clicking back in the terminal pane after resizing. Silly me.

It looks like when you grab the divider to resize the terminal pane the terminal stops handling keyboard events but still looks focused (the cursor blinks). Looking at the developer tools the pane still has the "active" class.

**Comment by MoOx** [comment]
So this might seems related to #30

**Comment by ssfrr** [comment]
Definitely could be related. There's a little bit of difference in that when you switch panes from the keyboard (as described in #30) the terminal pane loses the "active" class, whereas in this issue when you click the divider it keeps the "active" class but just doesn't handle keyboard input.

Strangely a normal editor window doesn't have this behavior. If the focus is in the editor and I resize the panes I can still type into the editor window without clicking to re-focus.
