### ISSUE TITLE
Ctrl+pgup displays `~` the first time

### ISSUE THREAD

**Issue by ssfrr** [f/atom-term2#148]
On Ubuntu `ctrl-pageup` and `ctrl-pagedown` are the keyboard shortcuts to switch tabs. If I'm in a terminal tab and I press `ctrl-pageup` it prints a tilde (`~`) to the screen, and then if I press it again it actually switches the tab.

**Comment by fbob** [comment]
same issue here on kubuntu 15.04

**Comment by yassinebha** [comment]
Any suggestion for Ubuntu (Unity) users?
