### ISSUE TITLE
Can "atom" replace "screen/tmux"?

### ISSUE THREAD

**Issue by serapath** [f/atom-term2#150]
Hi there, I'm a immediately became a big fan of this atom plugin.
I'm not sure where this project is headed, but the one thing that would be really great for me is:
- `To have an easy cross-platform way to save my files/terminal partitioned screen`

How I work
- I have several open `tabs` in multi-colomn/row `panes` next to `tree-view` to get project overview
- With `tab fullscreen` and `zen mode` i can focus on the work in the current tab
- with `ctrl-(shift)-tab` i move between tabs in a pane, with `alt-arrows` i move between panes

**In the past:**
- My tabs were only opened files showing me project content in my project folder hierarchy.
- One or many terminals, sometimes with multiple tabs and/or partitioned terminals

**What I hope for in the future:**
- Add `terminal tabs` in the panes next to my `project files`

**Benefit:**
I hope I can save my project related "terminal-views" together with my project related "file-views" in atom tabs & panes

**Current Problem:**
- My copy&paste works buggy when i use `atom-term2`
- When I `ctrl-shift-tab` into a terminal tab, the terminal doesnt get the focus
- When I close atom and restart it in the same folder, the terminal tabs are not restored

**Comment by MoOx** [comment]
For copy/paste issue see #23 
For the focus issue, see #6 

For the saving, it's might be done, but I am not sure how we can restore the appropriate path and terminal state. I know that tmux can do that using tmux-resurrect but doesn't make sense to add that in this plugin.

We can probably just restore terminal pane for a start. PR welcome.

**Comment by serapath** [comment]
Would it be possible that on closing atom, all the terminals opened as tabs will be read
* their `title`
* their `path`
and it will be saved to some extension related settings file, so that when they are re-opened, some commands are run on all of them to set the title and path to where they were they were the last time?
