### ISSUE TITLE
SIGINT Not Received by Term2

### ISSUE THREAD

**Issue by audrummer15** [f/atom-term2#155]
It seems that after starting a program in the term2 pane, you cannot end it with an interrupt. Ctrl+C doesn't trigger when being sent.

**Comment by MoOx** [comment]
It's working for me on latest Atom + OS X. I use ctrl+c all the times to kill my dev servers.

**Comment by audrummer15** [comment]
Hmm. I'm on version 1.0.0, Ubuntu 14.04.2. Running a packet replay program I've written, I can't force it to stop without closing the term2 pane.

**Comment by MoOx** [comment]
Can you run `top` command and kill it with ctrl+c ? (I can)

**Comment by audrummer15** [comment]
Yes, I can kill the ```top``` command with ctrl+c. However, the C++ program I've written doesn't die with ctrl+c, it does die with ctrl+z. However, killing it with ctrl+c from a regular terminal works fine. Will try to look into this more, just running low on time :)

**Comment by MoOx** [comment]
Ok cool. Good to know. Thanks.
