### ISSUE TITLE
Dancing Cursor (zsh?)

### ISSUE THREAD

**Issue by TylerLH** [f/atom-term2#157]
Running into an interesting problem where the cursor continues to "dance" when I open a term2 tab. I'm using zsh and OSX (10.10.3). Anyone else experiencing this?

![dancing_prompt_term2](https://cloud.githubusercontent.com/assets/528972/8637127/df7bd818-2836-11e5-95bb-a39bcbed8ede.gif)

**Comment by alecthegeek** [comment]
I'm getting in with Bash

**Comment by MoOx** [comment]
It's probably because you use a blinking thin character. I don't have issue with a fat non blinking square. That's definitely a bug, maybe a pty.js one. poke @chjj

**Comment by alecthegeek** [comment]
Not me. I have a fat steady cursor in iTerm2.

**Comment by chjj** [comment]
This is more likely to be an issue with term.js. Does this only happen in bash? I find it interesting that the strange effect occurs right after the PS1. What is your PS1? 

A pty.js dump of everything bash is outputting would be helpful (or `script -c bash bash.log` would be helpful too).

**Comment by Jonjoe** [comment]
@MoOx this is the same as #154 the only difference is I have blinking cursor turned off.
