### ISSUE TITLE
unresponsive empty panel opens if you refresh atom after using term2

### ISSUE THREAD

**Issue by jorgeartware** [f/atom-term2#16]
Ubuntu 12.04
Atom ver 0.101.0-1187d50
term2 ver 0.9.2

Steps to reproduce:
- `ctrl-alt-t` to open a term2 tab
- Then `ctrl-alt-r` to refresh atom

![20140604 ctrl-alt-r refresh behavior after opening and closing term2 tab - unable to close](https://cloud.githubusercontent.com/assets/2679372/3185990/f9ed89c2-ec9a-11e3-8f1c-e1cfb4bca1de.png)

**Comment by MoOx** [comment]
Cannot reproduce (or I didn't understand). Is it still relevant ?

**Comment by f** [comment]
I think, it "was" an Atom issue which is not reproducable right now.
