### ISSUE TITLE
Doesn't like Powerline Theme

### ISSUE THREAD

**Issue by jchannon** [f/atom-term2#164]
When the Term2 is opened it reads my zshrc file and reads my theme it says `character not in range` on this line:

`POWERLINE_GIT_INFO_LEFT=" %F{blue}%K{white}"$'\ue0b0'"%F{white}%F{black}%K{white}"$'$(git_prompt_info)$(git_prompt_status)%F{white}'`

I think its the `ue0b0` but I'm not sure how I can solve the issue.

Any ideas?

**Comment by MoOx** [comment]
Not really :/

**Comment by OJFord** [comment]
Sounds like your `locale` is out of whack.

Try `LC_CTYPE='en_GB.UTF-8' echo '\ue0b0'`; if that works, then type `locale` and export the options from something like:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

to your appropriate ISO code in the format `lang_LOCALE` e.g. `en_GB`, followed by `.UTF-8`.

**Comment by OJFord** [comment]
Actually -- don't bother: it resets to "C" as soon as you open a new terminal.

But that's what the issue is; maybe that helps for a fix @MoOx?

**Comment by jchannon** [comment]
Something has changed in that last version(s) as it now doesn't error and almost shows my terminal the same as what I have in iTerm2. See screenshot. iTerm2 is the bottom one and the Atom plugin the top.
<img width="603" alt="screen shot 2015-10-17 at 14 55 34" src="https://cloud.githubusercontent.com/assets/105126/10559080/55689116-74df-11e5-88c7-731f580579dc.png">

**Comment by jchannon** [comment]
I think this is an issue loading the font. In the screenshot below I have entered the font name as outlined in the red boxes into Term2 setting "Font Family" but it seems to load some default font. Any ideas why it might not be loading my font?
![screen shot 2015-10-24 at 15 54 57](https://cloud.githubusercontent.com/assets/105126/10711055/1a79e530-7a68-11e5-82bf-433a6ce5e143.png)

**Comment by jchannon** [comment]
No idea what happened but I got it working by typing in the font setting "Source Code Pro for Powerline"
