### ISSUE TITLE
希望可以支持中文字符输入

### ISSUE THREAD

**Issue by gavinning** [f/atom-term2#165]
Term2 is a great plugin,
I like it,
Hope can support Chinese character input.

Term2是一个非常棒的插件，
很喜欢，
希望可以支持中文字符输入。

![image](https://cloud.githubusercontent.com/assets/1996344/8928268/c643fe22-354f-11e5-86a8-1965248e3dba.png)

**Comment by MoOx** [comment]
PR welcome :)

**Comment by rguanghui** [comment]
The same problem :cry:

**Comment by DogLooksGood** [comment]
Neither input or display. Is it a problem from term.js?
