### ISSUE TITLE
Committed files are still highlighted after commit.

### ISSUE THREAD

**Issue by chrisduong** [f/atom-term2#169]
Hi,

If I use **Iterm 2** alone from **atom**, after I committed, committed files would clear theirs highlights.
But this not work for **atom-term2** plugin. I can be confused with those highlights.

I'm using atom-term2 version `0.9.14`

**Comment by chrisduong** [comment]
Hi,

I've just found out that **committed files** get highlight cleared after I committed in *iterm tab* but it takes longer than normal. Is there anyway to change this behavior

**Comment by MoOx** [comment]
Are you talking about files color in the tree view?
If so, it looks like it's an issue for atom tree-view.

**Comment by chrisduong** [comment]
Yes, files color in the tree view. But why it only happen with `atom-term2`, not with Terminal  nor `Git Plus` plugin.

**Comment by f** [comment]
It's not related to Term2 package. As far as I understand, TreeView somehow refreshes itself about git statuses. But clearly it's an issue of Atom.
