### ISSUE TITLE
Running Grunt in Term2 exceeds scrollable view area

### ISSUE THREAD

**Issue by jdsimcoe** [f/atom-term2#17]
I ran a Grunt command in a Term2 window and the output exceeds the scrollable area of the window. I still use `Ctrl` + `C` to kill the command but there is no way to see what the editor is doing. Here is an inspector view:

![screenshot](http://cl.ly/image/113P0y3F3F0k/Image%202014-06-06%20at%2012.38.06%20PM.png)

As you can see from my view of the Inspector window there are numerous more lines of code in Term2 that are obscured.

I'm running on OS X 10.9.3.

**Comment by jdsimcoe** [comment]
@f Has this issues been addressed?

**Comment by Lujaw** [comment]
+1 in ubuntu

**Comment by f** [comment]
This is because Atom's scroll feature is kinda buggy with non-editor panes which the Term2 is one of them.

Actually won't be able to search in terminal, so disabling CTRL/CMD-F is a better solution to me. What do you think @MoOx ?

**Comment by MoOx** [comment]
Maybe disable + warning (using atom bubbles) when people try to search in term2 tabs?
