### ISSUE TITLE
Suggestion: add a little padding on left side of terminal window

### ISSUE THREAD

**Issue by mzbik** [f/atom-term2#174]
Atom 1.0.7, OSX. Characters bump up against left side.

Suggest:
.term2 {
  .terminal {
    padding: 0;
    padding-left: 8px;

Or some other metric...

**Comment by f** [comment]
Normally, you can write it to your own stylesheet.

But I'll add this as an option :)

**Comment by ron-wolf** [comment]
Do you know whether it’s possible to color the padding in order to differentiate adjacent panes?
