### ISSUE TITLE
Segmentation fault 11 on unknown command

### ISSUE THREAD

**Issue by mzbik** [f/atom-term2#175]
OSX 10.10.5, all updates
Atom 1.0.7
Term2  0.9.15

Open a window and type a command that doesn't exist:

![image](https://cloud.githubusercontent.com/assets/2048333/9369717/edda274a-467f-11e5-8a2a-592417d080d2.png)

**Comment by f** [comment]
I couldn't reproduce this bug. Can you help me to reproduce it?

Thanks!

**Comment by mzbik** [comment]
I tracked it down to using the macports version of bash instead of the Apple-supplied version.
