### ISSUE TITLE
Opening multiple term2 windows in the same pane crashes Atom

### ISSUE THREAD

**Issue by sporkmonger** [f/atom-term2#176]
<img width="1440" alt="screen shot 2015-08-19 at 3 07 03 pm" src="https://cloud.githubusercontent.com/assets/1778/9370300/19122666-4684-11e5-8b18-d0d15a1513cd.png">
<img width="1440" alt="screen shot 2015-08-19 at 3 07 27 pm" src="https://cloud.githubusercontent.com/assets/1778/9370303/1e103a18-4684-11e5-987d-fcff99e7ca65.png">
<img width="1440" alt="screen shot 2015-08-19 at 3 07 40 pm" src="https://cloud.githubusercontent.com/assets/1778/9370307/233cc7a4-4684-11e5-855a-dba834f48342.png">

**Comment by sporkmonger** [comment]
Also note the weird whitespace at the bottom of the first screenshot, which happens when you have two terminals open and you jump focus between them.

**Comment by vlsd** [comment]
I'm having a similar issue (or maybe the exact same issue?) with only one term2 pane opened, and a bunch of other files in split panes. I'm having a hard time reproducing it reliably, although it always happens eventually. Is there an error log, or dump or whatever that I can look at after the crash?

**Comment by KeKs0r** [comment]
I experience the same thing, everytime I open a second terminal pane. (which is a lot since one terminal is always running my server and the other one is the one I actually interact with)

**Comment by jchannon** [comment]
I just came across this exact same issue
