### ISSUE TITLE
seems if move cursor to a character, this character will be overlapped by white cursor 

### ISSUE THREAD

**Issue by ethe** [f/atom-term2#177]
like this ![2015-08-30 13 09 11](https://cloud.githubusercontent.com/assets/12211036/9565788/56f661ee-4f18-11e5-907b-90b62053c790.png)

**Comment by f** [comment]
I need more explanation. Can you make a gif or something to make me understand the problem?

**Comment by ethe** [comment]
![out](https://cloud.githubusercontent.com/assets/12211036/9571010/b321c376-4fc9-11e5-98e2-f9d76fb28c1c.gif)
like this, white cursor cover the character completely
