### ISSUE TITLE
Excessively Fast Scrolling on Macbook Trackpad

### ISSUE THREAD

**Issue by poltj18** [f/atom-term2#181]
I find the scroll speed to be way to fast when using the trackpad. It seems to work well with the mouse.

**Comment by ron-wolf** [comment]
The problem: it scrolls five lines at a time, but with a max speed that’s far too slow to be useful for skimming.

**Comment by RyanCodrai** [comment]
The scrolling speed is way too fast, using macbook pro

**Comment by Sterbic** [comment]
+1 on the trackpad issue

A parameter to tweak the scroll speed would be nice.

**Comment by blond** [comment]
+1

**Comment by benjaminalt** [comment]
I'm having the same problem on windows. The scroll speed is a multiple of what I get in Chrome or any native app.
