### ISSUE TITLE
Some keybindings do not work (Atom 1.7.2, term2 0.9.21, Ubuntu 16.04)

### ISSUE THREAD

**Issue by SubhamSatyajeet** [f/atom-term2#185]
The keybindings:

ctrl + alt + up
ctrl + alt + right
ctrl + alt + down
ctrl + alt + left
ctrl + k, t, t
ctrl + k, t, up
ctrl + k, t, right
ctrl + k, t, down
ctrl + k, t, left
cmd + k, t, t
cmd + k, t, up
cmd + k, t, right
cmd + k, t, down
cmd + k, t, left

Don't work. Only the ctrl+alt+T works for opening a new separate terminal window.
This hasn't been fixed since Atom 1.0.11.

**Comment by ron-wolf** [comment]
Try redefining those keybindings to be active in scope `.platform-darwin`, in either your own (`~/.atom/keymap.cson`) or the internal (`~/.atom/packages/term2/keymaps/term2.cson`) keymap—preferably the first. Here’s my keymap file, for instance:

```CSON
'.platform-darwin':
    'cmd-k t t':     'term2:open'
    'cmd-k t right': 'term2:open-split-right'
    'cmd-k t left':  'term2:open-split-left'
    'cmd-k t up':    'term2:open-split-up'
    'cmd-k t down':  'term2:open-split-down'
```

The default scope is `atom-text-editor`, which seems to require the keyboard to have focus, whereas `.platform-darwin` is pretty much universal within Atom. Keep in mind, however, that I’m running OS X; if you’re on Windows, that may be a different story.

**Comment by andy3rdworld** [comment]
I'm having same issue as @SubhamSatyajeet. Redefining keybindings did not fix. I'm using Linux Mint 17 distro. Clicking on menu item: Packages > Term 2 > Open Terminal in [...] does not open either.

**Comment by ron-wolf** [comment]
Whoops, just noticed you’d already said you were on Ubuntu. Scoping still holds, though.
