### ISSUE TITLE
Unable to install Atom-Term2  0.9.20 in Atom version 1.0.15

### ISSUE THREAD

**Issue by mdixon47** [f/atom-term2#188]
When Installing form the command line or the Atom installer, I am getting the error below: 

> pty.js@0.2.13 install /private/tmp/apm-install-dir-115820-1733-x8gj1v/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:844
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:844:23)
    at startup (node.js:58:13)
    at node.js:935:3
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/malikdixon1/.atom/.apm/.apmrc" "--userconfig" "/Users/malikdixon1/.atom/.apmrc" "install" "/private/tmp/d-115820-1733-jfch1l/package.tgz" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/apm-install-dir-115820-1733-x8gj1v/npm-debug.log

A hand in the right direction would be helpful.

**Comment by antmachine** [comment]
same here

**Comment by dileepponna** [comment]
me too
