### ISSUE TITLE
Terms opened with "term-open" (ctrl-alt-t) require two focus clicks to accept input

### ISSUE THREAD

**Issue by sjuvonen** [f/atom-term2#191]
Terms that are opened using command "term-open" (ctrl-alt-t) into an existing pane require two clicks in order to accept input. This is different from terms that are opened using one of the open-split-\* commands, for which a single click is enough.

How to produce:
- Have an empty pane
- Open a new term using term-open (default: ctrl-alt-t)
- Type in to verify it accepts input
- Click to focus some other view
- Click back to term and type -> does not accept input
- Click the same term again -> input is accepted

**Comment by yomed** [comment]
You should be able to use the tab key to focus it if you prefer (not a fix, just a workaround).
