### ISSUE TITLE
Atom freezed when term2 splits screen on second Mac monitor

### ISSUE THREAD

**Issue by ppalladino** [f/atom-term2#202]
On a MacBook Pro v10.10.5 (Retina, 13-inch, Late 2012) splitting screen on second monitor causes Atom to permanently freeze. 

Reproduce:
1) Make Atom fullscreen on second monitor (not the laptop's monitor)
2) Key in ctrl+alt+right
3) Term2 splits the screen as expected but Atom is frozen .

**Comment by lleolin** [comment]
Same issue MacBook Pro (Retina, 15-inch, Late 2013) v10.11.1
