### ISSUE TITLE
Installing “term2@0.9.21” failed.

### ISSUE THREAD

**Issue by MarkPuchalaII** [f/atom-term2#216]
Not sure how to go about this, but it said to contact you.
So I just copy/pasted the message for you.

What's the usual method to sharing issues like this?

> pty.js@0.2.13 install C:\Users\MARKBE~1\AppData\Local\Temp\apm-install-dir-1151123-6720-120wlnj\node_modules\term2\node_modules\pty.js
> node-gyp rebuild

C:\Users\MARKBE~1\AppData\Local\Temp\apm-install-dir-1151123-6720-120wlnj\node_modules\term2\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\Mark Belain\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Mark Belain\AppData\Local\atom\app-1.3.2\resources\app\apm\bin\node.exe" "C:\Users\Mark Belain\AppData\Local\atom\app-1.3.2\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Mark Belain\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Mark Belain\.atom\.apmrc" "install" "C:\Users\MARKBE~1\AppData\Local\Temp\d-1151123-6720-1cf0kl2\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by atian25** [comment]
+1 for this

**Comment by PuYart** [comment]
+1！

**Comment by coderant** [comment]
Same here.

```
10 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/1m/r6rbxfqs3qs0jfyq5f4ph35w0000gn/T/apm-install-dir-116115-2366-im0cf1/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Meth/.atom/.apm/.apmrc" "--userconfig" "/Users/Meth/.atom/.apmrc" "install" "/private/var/folders/1m/r6rbxfqs3qs0jfyq5f4ph35w0000gn/T/d-116115-2366-5rg929/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
```

**Comment by SeanPlusPlus** [comment]
+1

**Comment by CristyTarantino** [comment]
+1

**Comment by JonthueM** [comment]
SAME HERE 
C:\Users\DEV-MI~1\AppData\Local\Temp\apm-install-dir-11635-1220-13475o\node_modules\term2\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\Dev-Michel\AppData\Local\atom\app-1.6.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Dev-Michel\\AppData\\Local\\atom\\app-1.6.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dev-Michel\\AppData\\Local\\atom\\app-1.6.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Dev-Michel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Dev-Michel\\.atom\\.apmrc" "install" "C:\\Users\\DEV-MI~1\\AppData\\Local\\Temp\\d-11635-1220-6wx81m\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by K4zuki** [comment]
a pull request have been merged and may fix some of issue(but not yet packed for atom):
https://github.com/f/atom-term2/pull/211
for windows users, try this one:
https://github.com/f/atom-term2/issues/222#issuecomment-204255317

**Comment by ghaderian** [comment]
still getting this

**Comment by ozo2003** [comment]
still an error
