### ISSUE TITLE
Cannot type the letter "k" in term2

### ISSUE THREAD

**Issue by bendavis78** [f/atom-term2#217]
I tried this with a fresh config dir. Basically one cannot type the letter "k" or "K" in the terminal. All other letters seem to work. The keybinding resolver shows that the key is not bound to anything.

**Comment by RaviTezu** [comment]
I am on Ubuntu 15.10 running Atom 1.0.19 and I see the similar issue. When ever I type "k" in the terminal, it shows a pop-up(See attached image) and however, I can see the typed "k" then after. Hope this may help, in fixing the issue. 
![term2](https://cloud.githubusercontent.com/assets/3827937/13329183/811ba640-dc18-11e5-87f0-58ae8b7ea5ab.png)

Thanks for the plugin. I would like to have a shortcut for switching between the file tabs and terminal.
