### ISSUE TITLE
Fixes to make atom-term2 work in Windows

### ISSUE THREAD

**Issue by vuki** [f/atom-term2#222]
I wrote this in the atom-term3 repository, but that project seems to be dead. Since these issues are also valid for atom-term2, I will repost it here.

I've been trying to install atom-term2 on Windows 7. I've succeeded after some hacking into the code. I'm writing this as a sugestion to make some code changes to allow other Windows users install the module.

**Problem 1**: pty.js does not compile on Windows.
Solved by replacing pty.js with ptyw.js:
- package.json, line 26: pty.js -> ptyw.js
- pty.coffee, line 3 -> require 'ptyw.js'

I don't know if ptyw can be used instead of pty on Mac and Linux though.

**Problem 2**: after loading Atom, I get the following error:
`TypeError: Cannot read property 'toLowerCase' of undefined
    at file:///C:/Users/Greg/.atom/packages/atom-term2/index.coffee:94:33`

This results from this code:

```
    default: do ({SHELL, HOME}=process.env) ->
      switch path.basename SHELL.toLowerCase()
```

On Windows, SHELL variable is not defined, hence toLowerCase generates the error.

Dirty fix:

```
  shellArguments:
    type: 'string'
    default: do ({SHELL, HOME}=process.env) ->
      if process.platform is not 'win32'
        switch path.basename SHELL.toLowerCase()
          when 'bash' then "--init-file #{path.join HOME, '.bash_profile'}"
          when 'zsh'  then "-l"
          else ''
      else ''
```

**Problem 3**: error in console after starting the terminal:

```
File not found: C:\Windows\WindowsPowerShell\v1.0\powershell.exe 
Error: File not found: C:\Windows\WindowsPowerShell\v1.0\powershell.exe
```

This path is hardcoded in pty.coffee, line 12:

```
        shell = path.resolve(process.env.SystemRoot, 'WindowsPowerShell', 'v1.0', 'powershell.exe')`
```

There is no such path on my PC. Besides, it is sufficient to enter 'powershell.exe', it will be found. And also besides, i much prefer using cmd.exe. Hence changing the line to:
`shell = 'cmd.exe'`
fixed the problem for me. Perhaps this should be configurable.

**Problem 4**: error after pressing K key:

```
Uncaught ReferenceError: isMac is not defined
C:\Users\Greg\.atom\packages\atom-term2\node_modules\atom-term.js\src\term.js:2528
```

Right, it's not defined. This should be (line 2528):

```
      if ((!this.isMac && ev.ctrlKey) || (this.isMac && ev.metaKey)) {
```

Now, no error but 'k' key doesn't work. Fixed by adding a missing 'break' (without it, k was changed to F1):

```
    // CTRL-K
    case 75:
      if ((!this.isMac && ev.ctrlKey) || (this.isMac && ev.metaKey)) {
        this.clear();
        return cancel(ev);
      }
      break;
```

Now the terminal works, but I don't have the _Settings_ button in Atom packages page for atom-term2. I think it should be there and I don't know why it doesn't show. No errors are printed in the console. The _Disable_ button is not working as well. Also, one quirk is that the terminal prints some 'Not enough storage is available to complete this operation' nonsense. 

I hope this will be helpful, maybe at least some of these changes will be incorporated into the code.

**Comment by K4zuki** [comment]
First of all, :+1:!

Your modification set suppressed error from atom and tab appears, but it closes immediately.
I could see some error messages before crashes.
The message changes between pointing `powershell.exe` or `cmd.exe` in `pty.coffee` but
both cases message seems saying it cannot find `C:/busybox.exe`.

As soon as I placed `busybox.exe` directly under `C:\` drive root, it showed shell prompt.
but I could not find what is pointing to `C:\` drive root.
I am using busybox indeed but placed under `C:\bin`. I don't know this issue is environment dependent.

I am using **Windows7, Atom 1.6.0**.

Thanks,
K4zuki

**Comment by K4zuki** [comment]
I am doing confirmation with this fix on clean installed machine.
**Windows7 64bit, Atom1.6.0** with **git version 2.6.4.windows.1**(by Git for Windows)

## before start the fix:
Just go to package directory and clone current repository:
```
$ cd C:\Users\<username>\.atom\packages
$ git clone https://github.com/f/atom-term2
$ cd atom-term2
```
then try
```
$ apm install
```
We **do** know it fails, but need to do this to fix _Problem 4_ as files under `node_modules` directory will be downloaded by this.
At this point you would already see atom-term2 in "installed packages" menu in settings.

_From here we just follow instructions by @vuki_
## fix Problem 1:
```
./package.json (line 26)
./lib/pty.coffee (line 3)
```
## fix Problem 2:
```
./index.coffee (line 94)
```
## fix Problem 3:
```
./lib/pty.coffee (line 12)
```

## fix Problem 4:
```
./node_modules/atom-term.js/src/term.js (line 2528~)
```

## finally:
need to install VS2013 environment - minimum install took 2+ hours for me.
then
```
$ apm install .

Installing modules - done
```

hope this leads the instruction more easy-to-do direction

**Comment by K4zuki** [comment]
@vuki 
By some reason, when you'd create package named `term2` under `C:\Users\<username>\.atom\packages` from `Package Generator`,  you will see options page of _official_ `term2` package, and it affects your `atom-term2` package behavior.
This is very strange, but it just works ;)
