### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dhruvdutt** [f/atom-term2#224]
> npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the pty.js package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls pty.js
> npm ERR! There is likely additional logging output above.
> 
> C:\Users\dhruvdutt>npm owner ls pty.js
> chjj chjjeffrey@gmail.com
> TooTallNate nathan@tootallnate.net
> tootallnate nathan@tootallnate.net

**Comment by haisum** [comment]
can confirm, I am facing same on Ubuntu 16.04

**Comment by dhruvdutt** [comment]
@f

**Comment by xlearner** [comment]
same issue on ubuntu 16.04

**Comment by niklasnson** [comment]
same error on macOS 10.12

**Comment by nemo** [comment]
Same error on Ubuntu 16.04. Latest pty.js install works, just need to update the dependency!

**Comment by Zundrium** [comment]
Having the same issue here, please update!

**Comment by wolendranh** [comment]
Mac OS Siera same issue.
