### ISSUE TITLE
npm ERR! Tell the author that this fails on your system: npm ERR!     node-gyp rebuild

### ISSUE THREAD

**Issue by tomptaylor** [f/atom-term2#225]
Installing “term2@0.9.21” failed.Hide output…

> pty.js@0.2.13 install /private/var/folders/wj/6yhyd3mj7xzf281vfzlc1fxc0000gn/T/apm-install-dir-116516-17691-15j45wx/node_modules/term2/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:41:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:53:40: note: candidate function not viable: 2nd argument ('const char _') would lose const qualifier
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:38:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                       ^
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node_buffer.h:46:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:772:12: error: no viable conversion from returned value of type 'v8::MaybeLocalv8::Object' to function return type 'v8::Localv8::Object'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocalv8::Object' to 'const v8::Localv8::Object &' for 1st argument
class Local {
      ^
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object &&' for 1st argument
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:326:13: note: candidate template ignored: could not match 'S _' against 'v8::MaybeLocalv8::Object'
  V8_INLINE Local(S_ that)
            ^
In file included from ../src/unix/pty.cc:20:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node.h:42:
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    _(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization 'v8::Localv8::Primitive::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node.h:42:
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Boolean _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization 'v8::Localv8::Boolean::Localv8::Value' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node.h:42:
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Function _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization 'v8::Localv8::Function::Localv8::Value' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

In file included from ../src/unix/pty.cc:20:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/src/node.h:42:
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:221:5: error: assigning to 'v8::Object _volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/TomTaylor/.atom/.node-gyp/.node-gyp/0.36.8/deps/v8/include/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T_ volatile_>(0)) = static_cast<S_>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization 'v8::Localv8::Object::Localv8::Value' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))

```
                         ^
```

10 errors generated.
make: **\* [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/TomTaylor/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/Users/TomTaylor/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/wj/6yhyd3mj7xzf281vfzlc1fxc0000gn/T/apm-install-dir-116516-17691-15j45wx/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/TomTaylor/Downloads/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/TomTaylor/Downloads/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/TomTaylor/.atom/.apm/.apmrc" "--userconfig" "/Users/TomTaylor/.atom/.apmrc" "install" "/private/var/folders/wj/6yhyd3mj7xzf281vfzlc1fxc0000gn/T/d-116516-17691-106d22z/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/wj/6yhyd3mj7xzf281vfzlc1fxc0000gn/T/apm-install-dir-116516-17691-15j45wx/npm-debug.log

Uninstalling “terminal-plus” failed.Show output…
Community Packages1/1

0.14.5107,846
terminal-plus A terminal package for Atom, complete with themes and more.
jeremyramin
UninstallDisable
Core Packages0/77

Development Packages0/0

Git Packages0/0

**Comment by RomanADavis** [comment]
I had a similar problem when I tried to install term2 on my own system

PS C:\Users\TOSHIBA\Desktop\Data Structures> apm install term2
Installing term2 to C:\Users\TOSHIBA\.atom\packages failed

> pty.js@0.2.13 install C:\Users\TOSHIBA\AppData\Local\Temp\apm-install-dir-11667-18956-17087e9\node_modules\term2\node_
modules\pty.js
> node-gyp rebuild


C:\Users\TOSHIBA\AppData\Local\Temp\apm-install-dir-11667-18956-17087e9\node_modules\term2\node_modules\pty.js>if not de
fined npm_config_node_gyp (node "C:\Users\TOSHIBA\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): erro
r MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\TOSHIBA
\AppData\Local\Temp\apm-install-dir-11667-18956-17087e9\node_modules\term2\node_modules\pty.js\build\deps\winpty\winpty-
agent.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): erro
r MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\TOSHIBA
\AppData\Local\Temp\apm-install-dir-11667-18956-17087e9\node_modules\term2\node_modules\pty.js\build\deps\winpty\winpty.
vcxproj]

gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\TOSHIBA\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\TOSH
IBA\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Use
rs\\TOSHIBA\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\TOSHIBA\\.atom\\.apmrc" "install" "C:\\Users\\TOSHIBA\\AppD
ata\\Local\\Temp\\d-11667-18956-82qsoa\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by alvarolm** [comment]
same here
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.5.7-202.fc23.x86_64
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1161023-16988-1j8i5yt/node_modules/term2/node_modules/pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1161023-16988-1j8i5yt/package.json'
npm WARN apm-install-dir-1161023-16988-1j8i5yt No description
npm WARN apm-install-dir-1161023-16988-1j8i5yt No repository field.
npm WARN apm-install-dir-1161023-16988-1j8i5yt No README data
npm WARN apm-install-dir-1161023-16988-1j8i5yt No license field.
npm ERR! Linux 4.5.7-202.fc23.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/alvarolm/.atom/.apm/.apmrc" "--userconfig" "/home/alvarolm/.atom/.apmrc" "install" "/tmp/d-1161023-16988-ydy2hb/package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.2.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1161023-16988-1j8i5yt/npm-debug.log
npm ERR! code 1
