### ISSUE TITLE
mouse scroll don't work

### ISSUE THREAD

**Issue by malko** [f/atom-term2#3]
Using zsh as terminal, it seems impossible to scroll the output up using the mouse, even using keyboard shift-pageup :worried: 

keep up the good work

**Comment by zchee** [comment]
+1

**Comment by Lujaw** [comment]
doesn't work on mine too..

**Comment by valerino** [comment]
yep, same issues with zsh here aswell (osx 10.10.3). except that, is perfect!!

**Comment by jchannon** [comment]
yup same issue but its great apart from that :smile: :+1:

**Comment by MoOx** [comment]
Is it still relevant ?

**Comment by ssfrr** [comment]
I'm seeing this behavior. If I run a few commands in zsh and then run `bash`, the scrolling works (even going up into my zsh history). As soon as I type `exit` and drop back into ZSH the scrolling stops working. I'm seeing it on both linux and OSX.

**Comment by shangx** [comment]
Same issue here on linux, it seems to affect only zsh though :(. Works fine with bash

**Comment by MoOx** [comment]
That's a bit weird because I am using zsh, and I can scroll back... That said, I don't see any scrollbar.

**Comment by malko** [comment]
here I can scroll whit Ctr+Page_up / Ctrl+Page_down but mouse wheel still have no effect

**Comment by peduxe** [comment]
I'm on linux at it does work with Shift + keys or page up/down, althought, mouse scroll doesn't do nothing.
