### ISSUE TITLE
Wrapping at weird lengths/spacing issues

### ISSUE THREAD

**Issue by jamestillercode** [f/atom-term2#34]
![image](https://cloud.githubusercontent.com/assets/2343130/3832015/bec2d228-1d99-11e4-8890-57c6810bdc27.png)

The words are doing a sort of reverse wrap per line, where the first character of the next line appears at the end of the previous line. This happens occasionally with a new session, even when you have word wrap turned off. It most notably happens with ls, but it's happened with outputs of other commands as well.

**Comment by X-Ryl669** [comment]
Same for me, it also does this for the initial "term" package.

**Comment by DabeDotCom** [comment]
+1

It appears to have to do with multiple 'tab' characters — i.e., chr(09):

```
perl -e 'print "1234567\t\t1234567\t\t1234567\n"'   # OKAY
perl -e 'print "12345678\t\t1234567\t\t1234567\n"'  # FAIL
perl -e 'print "1234567\t\t12345678\t\t1234567\n"'  # FAIL
perl -e 'print "1234567\t\t1234567\t\t12345678\n"'  # OKAY

perl -e 'print "12345678\t1234567\t\t1234567\n"     # OKAY
perl -e 'print "12345678\t1234567\t\t\t1234567\n"   # FAIL

perl -e 'print "A\t\tB\t\tC\t\tD\n"'   # FAIL
```
