### ISSUE TITLE
Some commands do not work ($PATH issue?)

### ISSUE THREAD

**Issue by ar1g** [f/atom-term2#50]
When using Term2 (which is a great plugin, BTW!), the atom command to open all source files in a directory does not work and shows error:

LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

**Comment by MoOx** [comment]
The command need backticks

```
'autoRunCommand': 'login -f `whoami`'
```

**Comment by MoOx** [comment]
With the help of @magsout we found that pty.js doesn't have the exact same prompt/env that when you are in Terminal.app. Not sure why. Maybe it's related to bash. I don't have this issue with zsh.
Can you confirm that you are all using bash and tell us:

- have you `~/.profile` ?
- have you `~/.bash_profile` ?
- have you `~/.bashrc` ?
- share `echo $PATH` from Terminal.app
- share `echo $PATH` from atom-term2

That might helps up to fix that or at least provide accurate documentation.

**Comment by ericconrad** [comment]
Hey MoOx. I have `~/.bash_profile`, do not have `~/.profile` or `~/.bashrc`. 

`echo $PATH` from Terminal.app: `/Users/ericconrad/.node/bin:/Users/ericconrad/.ruby/default/bin:/usr/local/bin:/usr/local/sbin:/Users/ericconrad/.node/bin:/Users/ericconrad/.ruby/default/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`

`echo $PATH` from atom-term2:
`/Users/ericconrad/.node/bin:/Users/ericconrad/.ruby/default/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by MoOx** [comment]
So after investigating a little, it seems that GUI app doesn't get `/etc/paths` (and `/usr/local/bin` come from this place).
There is some workaround for OS X 10.9-, but OS X 10.10+ doesn't execute `/etc/launchd.conf`.
So, in order to get the right `PATH` in atom-term2 context, I have added this not really pretty line in my .zshrc (should work for some other envs)

```
export PATH=$(cat /etc/paths | xargs | tr " " :)
```

This way, I have the same PATH in Terminal.app or in Atom.app term2 plugin.

I will probably close this issue by adding both solutions in the README.

**Comment by DannyvanderJagt** [comment]
@MoOx Thank you, that line fixed it for me. (OS X 10.10.4)

**Comment by MoOx** [comment]
Recently this line cause me some issues for something missing in PATH.
So for now I hardcoded it in my zshrc

```bash
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
```

**Comment by art-eltyshev** [comment]
In spite of completely redefining `PATH` in `.bashrc`, it would be better to add auto run command, that will add missing dirs
`export PATH="$PATH:/usr/local/bin:/usr/local/sbin"`

Your `.bashrc` config is not modified and term2 is working =)

**Comment by f** [comment]
I'll check if I can do anything to make it possible, but Atom doesn't allow to do it. I think it's because Atom opens the Terminal as child process which doesn't allow to use open native applications.

Related to https://github.com/f/atom-term2/issues/133

**Comment by nitintutlani** [comment]
The following works:
```
term2:
  autoRunCommand: 'bash'
```

**Comment by bendavis78** [comment]
I get the same error when calling atom from command line:
```
$ /usr/share/atom/atom: bad option: --executed-from=/home/ben/.atom/packages/minimize-panes
/usr/share/atom/atom: bad option: --pid=15244
```

My path contains all the correct bin directories:
```
./node_modules/.bin
/home/ben/.gem/ruby/2.2.0/bin
/home/ben/.local/bin
/home/ben/.pub-cache/bin
/home/ben/configs/bin
/usr/local/bin
/usr/bin
/bin
./node_modules/.bin
/home/ben/.gem/ruby/2.2.0/bin
/home/ben/.local/bin
/home/ben/.pub-cache/bin
/home/ben/configs/bin
/usr/local/bin
/usr/bin
/bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/opt/android-sdk/platform-tools
/usr/lib/jvm/default/bin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
/home/ben/.gem/ruby/2.2.0/bin
/home/ben/.gem/ruby/2.2.0/bin
```

I've tried using `bash` as my autorun command as well as `login -f $(whoami)`
