### ISSUE TITLE
Piping text broken

### ISSUE THREAD

**Issue by edubkendo** [f/atom-term2#58]
I wasn't able to get text to pipe from the text buffer to the terminal, so I poked around in the source a bit and fixed it like this:

``` coffee
# index.coffee:108-128
    pipeTerm: (action)->
      editor = atom.workspace.getActiveEditor()
      stream = switch action
        when 'path'
          editor.getBuffer().file.path
        when 'selection'
          editor.getSelectedText()

      if stream and @focusedTerminal
        if Array.isArray @focusedTerminal
          [pane, item] = @focusedTerminal
          pane.activateItem item
        else
          item = @focusedTerminal

        item.ptyProcess.send(
          event: 'input',
          text: stream.trim()
        )

        item.focus()
```

This seems to work. I was disappointed to find there was no way to pipe text back out, from the terminal to the text buffer, and I couldn't even get highlighting it with the mouse and copy/past to work. If I highlight the text, pressing cmd+c or ctrl+shift+c fail to do anything, and right-clicking doesn't either. Really need to be able to send text back over from the REPL for this to be as useful as it could be.

Thanks for all your hard work, this is nicely done.

**Comment by MoOx** [comment]
PR is welcome.
