### ISSUE TITLE
text wrapping overlap

### ISSUE THREAD

**Issue by kmdavis** [f/atom-term2#77]
When text wraps in the console, it winds up printing on top of whatever is on the next line with very bizarre looking results:
![screen shot 2014-12-12 at 10 48 30 am](https://cloud.githubusercontent.com/assets/132806/5414387/a7c6c7fc-81ec-11e4-97ba-0f402a8dbfe4.png)
![screen shot 2014-12-12 at 10 49 08 am](https://cloud.githubusercontent.com/assets/132806/5414390/a99a6e26-81ec-11e4-9129-8c2e7d6d4c69.png)

**Comment by b3nj4m** [comment]
I'm having this problem as well with version `0.9.4`, atom version `0.176.0`.

**Comment by enthalpy-yan** [comment]
I got the same issue,  but I found it only happens when I use left or right panel for the console. atom  0.181.0,  atom term2 0.9.4

**Comment by seanpclark** [comment]
Do you have softWrap enabled? If so, try setting `softWrap: false` under term2 in your config file.

**Comment by blimmer** [comment]
I'm experiencing the same problem.

![](https://i.imgur.com/mCWN80Z.png)

I tried setting `softWrap: false` in my term2 config, but I still get the same problem.

**Comment by MoOx** [comment]
We need to resize more often, we should probably listen to more events.
